version: '3'

networks:
  server:
    driver: 'bridge'

services:
  db:
    image: mysql
    container_name: db
    # command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: contacts
      MYSQL_ROOT_PASSWORD: contacts
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
  server:
    image: backend/server
    container_name: server_c
    build:
      dockerfile: Dockerfile
      context: './server'
    ports:
      - '3333:3333'
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    command: yarn dev
    environment:
      PORT: 3333
  web:
    stdin_open: true
    image: frontend/web
    container_name: web_c
    build:
      dockerfile: Dockerfile
      context: './web'
    ports:
      - '3000:3000'
    volumes:
      - ./web:/usr/app
      - /usr/app/node_modules
    command: yarn start
    environment:
      - CHOKIDAR_USEPOLLING=true
