version: '3'

services:
  server:
    image: backend/server
    container_name: server_c
    build:
      dockerfile: Dockerfile
      context: './server'
    ports:
      - '3333:3333'
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    command: yarn dev
    environment:
      PORT: 3333
  web:
    stdin_open: true
    # tty: true
    image: frontend/web
    container_name: web_c
    build:
      dockerfile: Dockerfile
      context: './web'
    ports:
      - '3000:3000'
    volumes:
      - ./web:/usr/app
      - /usr/app/node_modules
    command: yarn start
    environment:
      - CHOKIDAR_USEPOLLING=true
